apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-service
  namespace: petshop-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appointment-service
  template:
    metadata:
      labels:
        app: appointment-service
    spec:
      containers:
        - name: appointment-service
          image: petshop-appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: appointment-config
            - secretRef:
                name: appointment-secret
